[default]
cc = "cc"
ccflags = "-w -Wall -O3 "
cclibs = " -lm"
conf = "unix"

[mingw64]
cc = "x86_64-w64-mingw32-gcc-posix"
ccflags = "-w -Wall -O3 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601"
cclibs = "-lstdc++ -lpthread -lwinmm -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32"
conf = "mingw"

[mingw32]
cc = "i686-w64-mingw32-gcc-posix"
ccflags = "-w -Wall -O3 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 -m32"
cclibs = "-lstdc++ -lpthread -lwinmm -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32"
conf = "mingw"
